### ISSUE TITLE
 How can I get the FID, IS and Acc with PointNet++?

### ISSUE THREAD

**Issue by hangyi2000** [qizekun/VPP#1]
The paper reports the results of FID and IS on CLIP-Forge and Point-E. It confuses me how do you get the FID and IS of Point-E and CLIP-Forge. As far as I know CLIP-Forge gets the FID and IS based on a voxel classifier while Point-E gets the FID and IS based on a pointcloud classifier. Which pointnet++ classifier should I use?

**Comment by qizekun** [comment]
We use a pre-trained pointnet++ to extract point cloud features and calculate FID and IS according to formulas. For CLIP-Forge, we directly used the results reported in its paper.
