### ISSUE TITLE
大佬，代码啥时候开源

### ISSUE THREAD

**Issue by whx57** [qizekun/VPP#2]

**Comment by qizekun** [comment]
非常不好意思，最近一直在忙新项目和学校申请的事情，我会尽快把代码权重整理开源

**Comment by qizekun** [comment]
代码已经release

**Comment by whx57** [comment]
感谢感谢



---原始邮件---
发件人: "Zekun ***@***.***&gt;
发送时间: 2024年6月27日(周四) 晚上11:11
收件人: ***@***.***&gt;;
抄送: "Hu ***@***.******@***.***&gt;;
主题: Re: [qizekun/VPP] 大佬，代码啥时候开源 (Issue #2)




 
代码已经release
